### PR TITLE
Update vendor to include firestore adapter deps

### PR DESCRIPTION
**Pull request by utsavoza**

### CODE REVIEW

**Review by siddharthlatest — COMMENTED** [review]
@utsavoza Are you sure these are actually needed? I was able to build without this commit. It's possible that I already had them in my $GOPATH, but want to make sure we aren't adding anything that's not a dep of abc.

**Comment by utsavoza** [comment]
Unfortunately [`firebase.google.com/go`](https://firebase.google.com/docs/firestore/quickstart) pulls in a lot of dependencies. I tried to strip down to the required dependencies by installing it on my $GOPATH and then adding them to the vendor, but it still pulls in equal number deps to the project. Trying checking if you already have the following packages already in your $GOPATH.

- cloud.google.com/go
- firebase.google.com/go
- google.golang.org/{api, genproto, grpc}
...

Additionally, I had to update certain existing standard dependencies in the vendor that were conflicting with the internal usage in the fetched deps.

**Comment by siddharthlatest** [comment]
We should definitely add ones that are required, but also want to make sure we aren't adding any that may be unrelated. I already got the build working without including `a75ba13`, but that could be because I already had those deps in my $GOPATH from before. Want to confirm if I need to merge the `a75ba13` commit.

**Comment by utsavoza** [comment]
Without including `a75ba13` I was not able to build on my Linux system, but was able to build on my windows.

**Comment by siddharthlatest** [comment]
Thanks for confirming, I will include it.

**Pull request merged**
