### PR TITLE
update vendor.json with govendor . Added sqlite dependency

### PR DESCRIPTION
**Pull request by hackertron**
### Required for all PRs:

- [x] README.md updated (if needed)
- [ ] Passes `gofmt` and `golint`

### CODE REVIEW

**Review by utsavoza — COMMENTED** [review]
@hackertron You did update the `vendor.json` file but the dependencies weren't added to the `vendor` directory. Please make sure your are using `govendor` correctly. One way to verify is to run the docker command to successfully build the `!oss` version - `docker build --build-arg ABC_BUILD=noss -t abc .`

**Comment by hackertron** [comment]
but i did use govendor . I didn't edited the file manually :/ . I will try the command you gave above

**Comment by hackertron** [comment]
check it out now . I think what messed up was my i forgot to commit the vendor folder changes. i Compared  it again and found out it didn't pushed the changes of vendor folder. I have added them now .

**Comment by utsavoza** [comment]
@hackertron The changes looks good. One final change we require is to add a doc [here](https://github.com/appbaseio/abc/tree/dev/docs/importer/adaptors) that explains the CLI usage of the adaptor.

**Comment by hackertron** [comment]
Sure will do that !!

**Pull request merged**
