### PR TITLE
Redis: Vendor dependencies for Redis adaptor

### PR DESCRIPTION
**Pull request by palash25**
@siddharthlatest I just wanted to know what do you use to manage dependencies for abc dep or govender?

I used `govendor add github.com/go-redis/redis` for this PR btw

### CODE REVIEW

**Comment by utsavoza** [comment]
@palash25 Could you also verify if the PR successfully builds against both the build commands specified in the `abc-import` repository's `README.md`?

**Comment by palash25** [comment]
I just checked the `!oss` build is giving me some errors `use of internal package not allowed ` cc @utsavoza 

I am a little new to vendoring dependencies, could you help me out here a bit? Would you happen to know why the build fails?

**Comment by utsavoza** [comment]
@palash25 The following command `govendor add github.com/go-redis/redis` won't vendor in the internal packages to the project. In order to include the complete project tree try appending `/^` after the package name. e.g: `govendor add github.com/go-redis/redis/^`

**Comment by palash25** [comment]
Thanks @utsavoza it worked.

**Pull request merged**
